version: '3.8'

services:
  api:
    build:
      context: frontend
      dockerfile: Dockerfile  
    container_name: temp-model-container
    ports:
      - "8000:8000"
    networks:
      - myNetwork
    volumes:
      - ./data:/code/data 

  streamlit:
    build:
      context: backend
      dockerfile: Dockerfile  
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - api  # Asegura que la API se inicie antes que la app de Streamlit
    networks:
      - myNetwork 
    volumes:
      - ./data:/code/data 

networks:
  myNetwork:  # Nombre de la red que comparten los servicios
    name: myNetwork-1  # Nombre específico de la red
    driver: bridge  # El tipo de red, 'bridge' permite la comunicación interna entre los contenedores
