version: '3.8'

name: temp-preditcion-app

services:
  # Servicio de backend
  api:
    network_mode: host # Esta conectado a local
    image: temp-model-image:latest #Crear la imagen del modelo
    container_name: temp-model-container #Crear contenedor del modelo
    build:
      context: ./backend
      dockerfile: Dockerfile  
    ports:
      - "8000:8000" #Conectar al puerto 8000:8000
    volumes:
      - ./data:/code/data 

# Servicio de Frontend
  UI:
    network_mode: host  # Esta conectado a local
    image: temp-ui-image:latest #Crear la imagen del ui
    container_name: streamlit-app #Crear contenedor del ui
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    ports:
      - "8501:8501" #Conectar al puerto 8501:8501
    depends_on:
      - api  # Asegura que la API se inicie antes que la app de Streamlit
    volumes:
      - ./data:/code/data